# Generated by Django 2.2 on 2019-04-30 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ลากิจ', 'ลากิจ'), ('ลาป่วย', 'ลาป่วย')], max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('approve_status', models.CharField(choices=[('รอการอณุมัติ', 'รอการอณุมัติ'), ('อณุมัติ', 'อณุมัติ'), ('ไม่อณุมัติ', 'ไม่อณุมัติ')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
