# Generated by Django 2.2 on 2019-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reason',
            field=models.CharField(max_length=1000),
        ),
    ]
